
version: '3'

networks:
  restaurante_network:
    driver: bridge    

services:

#docker-compose -f docker-compose-restaurante.yml up restaurante_postgres_local
  restaurante_postgres_local:
    restart: always
    container_name: postgres-restaurante-local
    image: postgres:12.2-alpine
    ports:
      - 5234:5234
    networks:
      - restaurante_network
    environment:
      - POSTGRES_DB=restaurante
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123@mudar

  #docker-compose -f docker-compose-restaurante.yml up restaurante_pgadmin
  restaurante_pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: restaurante-pgadmin
    ports:
      - 15234:80
    networks:
      - restaurante_network
    environment:
      - PGADMIN_DEFAULT_PASSWORD=p0stgr3s
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
    depends_on:
      - restaurante_postgres_local